
package pmcg.fcn.prefeitura.cliente.viabilidade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ViabilidadePrefeituraWS", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ViabilidadePrefeituraWS {


    /**
     * 
     * @param xmlConfirmacaoRecebimentoConsulta
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaRecebimentoViabilidade", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.viabilidade.ConfirmaRecebimentoViabilidade")
    @ResponseWrapper(localName = "confirmaRecebimentoViabilidadeResponse", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.viabilidade.ConfirmaRecebimentoViabilidadeResponse")
    public String confirmaRecebimentoViabilidade(
        @WebParam(name = "xmlConfirmacaoRecebimentoConsulta", targetNamespace = "")
        String xmlConfirmacaoRecebimentoConsulta);

    /**
     * 
     * @param xmlRespostaAnaliseEndereco
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaRespostaAnaliseEndereco", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.viabilidade.ConfirmaRespostaAnaliseEndereco")
    @ResponseWrapper(localName = "confirmaRespostaAnaliseEnderecoResponse", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.viabilidade.ConfirmaRespostaAnaliseEnderecoResponse")
    public String confirmaRespostaAnaliseEndereco(
        @WebParam(name = "xmlRespostaAnaliseEndereco", targetNamespace = "")
        String xmlRespostaAnaliseEndereco);

    /**
     * 
     * @param xmlRequerimentoConsultaViabilidade
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaViabilidadesPendentes", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.viabilidade.RecuperaViabilidadesPendentes")
    @ResponseWrapper(localName = "recuperaViabilidadesPendentesResponse", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.viabilidade.RecuperaViabilidadesPendentesResponse")
    public String recuperaViabilidadesPendentes(
        @WebParam(name = "xmlRequerimentoConsultaViabilidade", targetNamespace = "")
        String xmlRequerimentoConsultaViabilidade);

}
