
package pmcg.fcn.prefeitura.cliente.empreendimento;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EmpreendimentoPrefeituraWSService", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", wsdlLocation = "file:/C:/WS/wsdl/prefeitura.wsdl")
public class EmpreendimentoPrefeituraWSService
    extends Service
{

    private final static URL EMPREENDIMENTOPREFEITURAWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pmcg.fcn.prefeitura.cliente.empreendimento.EmpreendimentoPrefeituraWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pmcg.fcn.prefeitura.cliente.empreendimento.EmpreendimentoPrefeituraWSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/WS/wsdl/prefeitura.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/WS/wsdl/prefeitura.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPREENDIMENTOPREFEITURAWSSERVICE_WSDL_LOCATION = url;
    }

    public EmpreendimentoPrefeituraWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpreendimentoPrefeituraWSService() {
        super(EMPREENDIMENTOPREFEITURAWSSERVICE_WSDL_LOCATION, new QName("http://www.jucemg.mg.gov.br/empreendimento/service", "EmpreendimentoPrefeituraWSService"));
    }

    /**
     * 
     * @return
     *     returns EmpreendimentoPrefeituraWS
     */
    @WebEndpoint(name = "EmpreendimentoPrefeituraWSPort")
    public EmpreendimentoPrefeituraWS getEmpreendimentoPrefeituraWSPort() {
        return super.getPort(new QName("http://www.jucemg.mg.gov.br/empreendimento/service", "EmpreendimentoPrefeituraWSPort"), EmpreendimentoPrefeituraWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpreendimentoPrefeituraWS
     */
    @WebEndpoint(name = "EmpreendimentoPrefeituraWSPort")
    public EmpreendimentoPrefeituraWS getEmpreendimentoPrefeituraWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.jucemg.mg.gov.br/empreendimento/service", "EmpreendimentoPrefeituraWSPort"), EmpreendimentoPrefeituraWS.class, features);
    }

}
