
package pmcg.fcn.prefeitura.cliente.viabilidade;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ViabilidadePrefeituraWSService", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", wsdlLocation = "http://10.20.143.167:8080/empreendimento/service/ViabilidadePrefeituraWS?wsdl")
public class ViabilidadePrefeituraWSService
    extends Service
{

    private final static URL VIABILIDADEPREFEITURAWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pmcg.fcn.prefeitura.cliente.viabilidade.ViabilidadePrefeituraWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pmcg.fcn.prefeitura.cliente.viabilidade.ViabilidadePrefeituraWSService.class.getResource(".");
            url = new URL(baseUrl, "http://10.20.143.72:8080/empreendimento/service/ViabilidadePrefeituraWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.20.143.167:8080/empreendimento/service/ViabilidadePrefeituraWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VIABILIDADEPREFEITURAWSSERVICE_WSDL_LOCATION = url;
    }

    public ViabilidadePrefeituraWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ViabilidadePrefeituraWSService() {
        super(VIABILIDADEPREFEITURAWSSERVICE_WSDL_LOCATION, new QName("http://www.jucemg.mg.gov.br/empreendimento/service", "ViabilidadePrefeituraWSService"));
    }

    /**
     * 
     * @return
     *     returns ViabilidadePrefeituraWS
     */
    @WebEndpoint(name = "ViabilidadePrefeituraWSPort")
    public ViabilidadePrefeituraWS getViabilidadePrefeituraWSPort() {
        return super.getPort(new QName("http://www.jucemg.mg.gov.br/empreendimento/service", "ViabilidadePrefeituraWSPort"), ViabilidadePrefeituraWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ViabilidadePrefeituraWS
     */
    @WebEndpoint(name = "ViabilidadePrefeituraWSPort")
    public ViabilidadePrefeituraWS getViabilidadePrefeituraWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.jucemg.mg.gov.br/empreendimento/service", "ViabilidadePrefeituraWSPort"), ViabilidadePrefeituraWS.class, features);
    }

}
