
package pmcg.fcn.prefeitura.cliente.empreendimento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmpreendimentoPrefeituraWS", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpreendimentoPrefeituraWS {


    /**
     * 
     * @param xmlConfirmacaoRecebimentoEmpreendimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmacaoRecebimentoEmpreendimentoPelaPrefeitura", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.empreendimento.ConfirmacaoRecebimentoEmpreendimentoPelaPrefeitura")
    @ResponseWrapper(localName = "confirmacaoRecebimentoEmpreendimentoPelaPrefeituraResponse", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.empreendimento.ConfirmacaoRecebimentoEmpreendimentoPelaPrefeituraResponse")
    public String confirmacaoRecebimentoEmpreendimentoPelaPrefeitura(
        @WebParam(name = "xmlConfirmacaoRecebimentoEmpreendimento", targetNamespace = "")
        String xmlConfirmacaoRecebimentoEmpreendimento);

    /**
     * 
     * @param xmlConfirmacaoAlvaraInscricaoMunicipal
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaAlvaraInscricaoMunicipal", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.empreendimento.ConfirmaAlvaraInscricaoMunicipal")
    @ResponseWrapper(localName = "confirmaAlvaraInscricaoMunicipalResponse", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.empreendimento.ConfirmaAlvaraInscricaoMunicipalResponse")
    public String confirmaAlvaraInscricaoMunicipal(
        @WebParam(name = "xmlConfirmacaoAlvaraInscricaoMunicipal", targetNamespace = "")
        String xmlConfirmacaoAlvaraInscricaoMunicipal);

    /**
     * 
     * @param xmlRequerimentoEmpreendimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperaEmpreendimentosDeferidosParaPrefeitura", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.empreendimento.RecuperaEmpreendimentosDeferidosParaPrefeitura")
    @ResponseWrapper(localName = "recuperaEmpreendimentosDeferidosParaPrefeituraResponse", targetNamespace = "http://www.jucemg.mg.gov.br/empreendimento/service", className = "pmcg.fcn.prefeitura.cliente.empreendimento.RecuperaEmpreendimentosDeferidosParaPrefeituraResponse")
    public String recuperaEmpreendimentosDeferidosParaPrefeitura(
        @WebParam(name = "xmlRequerimentoEmpreendimento", targetNamespace = "")
        String xmlRequerimentoEmpreendimento);

}
